### PR TITLE
Updates for HACS

### PR DESCRIPTION
**Pull request by mikesalz**
Fingers crossed!

### CODE REVIEW

**Comment by rsampayo** [comment]
I see a green check.

**Comment by rsampayo** [comment]
whats the next step?

**Comment by mikesalz** [comment]
Yep!  It passed all of the required HACS validations!  I'm trying to figure out the next step now.  I think we need to fork HACS and add the integration.  But I'm not sure which repo.  Any ideas?

https://github.com/hacs

**Comment by rsampayo** [comment]
Ok, I forked the hacs repo, created a new branch, edited the integration file, add the name of your repo. I think all we need is to make a pull request. There is a checklist in the pull-request description, can you check if we are ready and fill out the links? :

Add SleepMe Thermostat integration to HACS repositories


## Checklist



- [ ] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [ ] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [ ] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [ ] The actions are passing without any disabled checks in my repository.
- [ ] I've added a link to the action run on my repository below in the links section.
- [ ] I've created a new release of the repository after the validation actions were run successfully.

## Links



Link to current release: <>
Link to successful HACS action (without the `ignore` key): <>
Link to successful hassfest action (if integration): <>

**Comment by rsampayo** [comment]
I created a new release https://github.com/rsampayo/sleepme_thermostat/releases/tag/v3.0.0

**Comment by rsampayo** [comment]
What I did to figure out what I needed to do was I look up the forks of the hacs integration and saw what they did. That might help you with any questions.

**Comment by rsampayo** [comment]
https://github.com/rsampayo/hacs-default/tree/add-sleepme-thermostat

**Comment by mikesalz** [comment]
Bleh....

image


If you want to create the pull request, here are the links you need for the bottom.  You can check all of the boxes.
> 
> Link to current release: <https://github.com/rsampayo/sleepme_thermostat/releases/tag/v3.0.0>
> Link to successful HACS action (without the `ignore` key): <https://github.com/rsampayo/sleepme_thermostat/actions/runs/10567107602/job/29275345914>
> Link to successful hassfest action (if integration): <https://github.com/rsampayo/sleepme_thermostat/actions/runs/10567107602/job/29275345709>

**Comment by rsampayo** [comment]
added you as a collaborator to that repo.

**Comment by mikesalz** [comment]
https://github.com/hacs/default/pull/2672

**Comment by mikesalz** [comment]
Check this out!  It is available to add through HACS.  Just not "built in" yet.  You can search for the repository and add it.  I just used HACS to get version 3.0


image

--------------------

image

**Comment by rsampayo** [comment]
pretty

**Comment by rsampayo** [comment]
I wonder if we can change the name to Sleepme Dock Pro.

**Comment by mikesalz** [comment]
Yeah, their branding is kind of all over the place. Sleepme, Dock Pro, Chilipad. Are you talking about renaming the entire repo or just the lable?

**Comment by rsampayo** [comment]
I think renaming the repo would be a pain in the butt but everything else we could change.

**Comment by mikesalz** [comment]
I’m not opposed to renaming it. I guess the official name is “Chilipad Dock Pro Bed Cooling System”.

I wouldn’t mind waiting until the PR is merged and the repo is officially added to the HACS search.

**Comment by rsampayo** [comment]
I agree, let's wait.

**Pull request merged**
